permalink: /:categories/:title

exclude: [".git", ".gitignore", ".gitmodules", "package.json", "README.md", "Gemfile", "Guardfile", "Gemfile.lock", "Makefile"]
title : coverflowjs

safe: true
lsi: false
pygments: true
